use_frameworks!

platform :ios, '9.0'

target 'TYSMBackgroundTask_Example' do
  pod 'TYSMBackgroundTask', :path => '../'

  target 'TYSMBackgroundTask_Tests' do
    inherit! :search_paths

    
  end
end
